export default {
  id: {
    title: 'Nama Situs',
    sidebarTitle: 'DaffaDev',
    description:
      'React perpustakaan bilah sisi dengan menu tarik-turun dan jumlah submenu bersarang yang tidak terbatas',
    dashboard: 'Beranda',
    components: 'Komponen',
    dropdown: 'Dropdown',
    submenu: 'Submenu',
    multiLevel: 'Multi Level',
    collapsed: 'Tumbangkan',
    ina: 'Bahasa 🇲🇨️',
    en: 'Inggris',
    image: 'Background image',
    new: 'BARU',
    withPrefix: 'Dengan Prefix',
    withSuffix: 'Sambungkan Dompet',
    viewSource: 'Kode Sumber',
    blog: 'Postingan',
    metamask: 'Metamask',
    walletconnect: 'WalletConnect',
    coinbase: 'CoinBase',
    madewith: 'Dibangun Dengan',
    by: 'oleh',
    author: 'unangningEU',
    join: 'Gabung dalam',
    movement: 'Pergerakan',
    and: 'dan',
    unlock: 'Buka',
    unique: 'Keunikan',
    art: 'Seni',
    discovered: 'Telusuri karya kami dibawah',
    view: 'Lihat Koleksi',
  },
  en: {
    title: 'Site Name',
    sidebarTitle: 'DaffaDev',
    description:
      'React sidebar library with dropdown menus and unlimited number of nested submenus',
    dashboard: 'Dashboard',
    components: 'Components',
    dropdown: 'Dropdown',
    submenu: 'Submenu',
    multiLevel: 'Multi Level',
    collapsed: 'Collapsed',
    ina: 'Bahasa 🇲🇨️',
    en: 'English',
    image: 'Background image',
    new: 'NEW',
    withPrefix: 'With Prefix',
    withSuffix: 'Connect Wallet',
    viewSource: 'View Source',
    blog: 'Blog Post',
    metamask: 'Metamask',
    walletconnect: 'WalletConnect',
    coinbase: 'CoinBase',
    madewith: 'Build with',
    by: 'by',
    author: 'unangningEU',
    join: 'Join the',
    movement: 'Movement',
    and: 'and',
    unlock: 'Unlock',
    unique: 'Unique',
    art: 'Art',
    discovered: 'Discover our work below',
    view: 'View Collection',
  },
};
